#!/bin/bash
source ../shell/common.sh

APP="foundations"

gvt fetch "github.com/davecgh/go-spew/spew"
gvt fetch "github.com/go-sql-driver/mysql"
gvt fetch "github.com/jmoiron/sqlx"
gvt fetch "github.com/youtube/vitess/go/pools"

FILES=$(ls *.go | sort)
for FILE in $FILES; do
	go run $FILE | tee "$FILE.txt"
done
