#!/bin/bash
NAME="gotwitter"
DOCKER_IMAGE="titpetric/gotwitter"
docker rm -f $NAME
docker run --net=party -e PORT=2000 --name=$NAME -d -p 8080:2000 $DOCKER_IMAGE
PREVSTATE=""
while true; do
	STATE=$(docker inspect $NAME | jq -r '.[].State.Health.Status')
	if [[ $STATE == $PREVSTATE ]]; then
		echo -n "."
	else
		if [ ! -z $PREVSTATE ]; then
			echo
		fi
		PREVSTATE=$STATE
		echo -n "State: $STATE "
	fi
	if [[ $STATE == "healthy" ]]; then
		echo
		exit 0
	fi
	sleep 1
done